# Generated by Django 3.2.4 on 2021-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='jane doe', max_length=200),
            preserve_default=False,
        ),
    ]
